/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 7000
    gain: 12.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    vel_control: 0
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 1.0
      sigma2_q_yaw: 50.0
      sigma2_q_r: 500.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-2

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

/vision_attacker:
  ros__parameters:
    trajectory:
      lag_time: 0.05
      air_k: 0.04
      yaw_fix: 0.5
      pitch_fix: -0.5
    fire_ctrl:
      car_attack_threshold: 85.0
      outpost_attack_threshold: 5.0
      threshold_fix: 0.0

    solver :
      max_yaw_acc: 50.0
      Q_yaw: [9e6, 0.0]
      R_yaw: [1.0]

      max_pitch_acc: 100.0
      Q_pitch: [9e6, 0.0]
      R_pitch: [1.0]

    planner:
      yaw_offset: 0.0 # degree 
      pitch_offset: 0.0 # degree 
      comming_angle: 60.0 # degree
      leaving_angle: 20.0 # degree
      decision_speed: 8.0 # rad/s
      high_speed_delay_time: 0.015 # s
      low_speed_delay_time: 0.015 # s

    
